import { deleteJson, getJson, patchJson, postJson, putJson } from "./client";
import type {
  Alert,
  AnalyzeResult,
  DataHealth,
  FundHoldingStock,
  FundNav,
  Indicator,
  MarketContext,
  PortfolioBuySimulation,
  PortfolioOverview,
  Report,
  Score,
  ScoreSignalSummary,
  ScoreStrategy,
  ScoreTrendRow,
  SyncDiagnostics,
  WatchlistItem,
} from "./types";

export const api = {
  dashboard: () => getJson<unknown>("/dashboard/overview"),
  dashboardToday: () => getJson<unknown>("/dashboard/today"),
  watchlist: () => getJson<WatchlistItem[]>("/watchlist"),
  addWatchlist: (data: Record<string, unknown>) => postJson<WatchlistItem>("/watchlist", data),
  removeWatchlist: (code: string) => deleteJson(`/watchlist/${code}`),
  syncWatchlistNav: () => postJson<Record<string, SyncDiagnostics>>("/watchlist/sync-nav"),
  syncFundNav: (code: string) => postJson<SyncDiagnostics>(`/funds/${code}/sync-nav`),
  analyzeFund: (code: string, generateReport = false) =>
    postJson<AnalyzeResult>(`/funds/${code}/analyze`, undefined, { generate_report: generateReport }),
  analysisStatus: (code: string) => getJson<unknown>(`/funds/${code}/analysis-status`),
  nav: (code: string) => getJson<FundNav[]>(`/funds/${code}/nav`),
  holdingStocks: (code: string) => getJson<FundHoldingStock[]>(`/funds/${code}/holdings/stocks`),
  syncHoldingStocks: (code: string) => postJson<{ fund_code: string; synced_rows: number }>(`/funds/${code}/holdings/stocks/sync`),
  calcIndicators: (code: string) => postJson<Indicator>(`/funds/${code}/calc-indicators`),
  indicators: (code: string) => getJson<Indicator>(`/funds/${code}/indicators`),
  calcScore: (code: string) => postJson<Score>(`/funds/${code}/calc-score`),
  score: (code: string) => getJson<Score>(`/funds/${code}/score`),
  topScores: (limit = 100) => getJson<Score[]>("/recommendations/top", { limit }),
  scoreStrategies: () => getJson<ScoreStrategy[]>("/scores/strategies"),
  scoreSummary: () => getJson<ScoreSignalSummary>("/scores/summary"),
  strategyTopScores: (strategy = "default", limit = 100) => getJson<Score[]>("/scores/top", { strategy, limit }),
  scoreTrend: (code: string) => getJson<ScoreTrendRow[]>(`/scores/trend/${code}`),
  dataHealth: () => getJson<DataHealth>("/data/health"),
  reconcile: (code: string) => getJson<unknown>(`/data/reconcile/${code}`),
  market: () => getJson<MarketContext[]>("/market/context"),
  syncMarket: () => postJson<unknown>("/market/sync"),
  alerts: () => getJson<Alert[]>("/alerts/unread"),
  generateAlerts: () => postJson<Alert[]>("/alerts/generate"),
  updateAlert: (id: number, status: string) => patchJson<Alert>(`/alerts/${id}`, { status }),
  portfolioOverview: () => getJson<PortfolioOverview>("/portfolio/overview"),
  portfolioDiagnosis: () => getJson<unknown>("/portfolio/diagnosis"),
  simulatePortfolioBuy: (data: { fund_code: string; amount: number }) =>
    postJson<PortfolioBuySimulation>("/portfolio/simulate-buy", data),
  portfolioTransactions: () => getJson<unknown[]>("/portfolio/transactions"),
  addTransaction: (data: Record<string, unknown>) => postJson<unknown>("/portfolio/transactions", data),
  deleteTransaction: (id: number) => deleteJson(`/portfolio/transactions/${id}`),
  addPosition: (data: Record<string, unknown>) => postJson<unknown>("/portfolio", data),
  updatePosition: (id: number, data: Record<string, unknown>) => putJson<unknown>(`/portfolio/${id}`, data),
  deletePosition: (id: number) => deleteJson(`/portfolio/${id}`),
  compareFunds: (codes: string[]) => getJson<unknown>("/funds/compare", { codes: codes.join(",") }),
  industryOverview: () => getJson<unknown[]>("/research/industry-overview"),
  riskReturn: () => getJson<unknown[]>("/research/risk-return"),
  correlationMatrix: () => getJson<unknown>("/correlation/matrix"),
  correlationPairs: () => getJson<unknown[]>("/correlation/pairs"),
  correlationReturns: (fundA: string, fundB: string) =>
    getJson<unknown[]>("/correlation/returns", { fund_a: fundA, fund_b: fundB }),
  generateCorrelationAlerts: () => postJson<Alert[]>("/correlation/alerts"),
  generateDailyReport: () => postJson<Report>("/reports/daily"),
  generateFundReport: (code: string) => postJson<Report>(`/reports/fund/${code}`),
  latestFundReport: (code: string) => getJson<Report | null>(`/reports/fund/${code}`),
  latestReport: () => getJson<Report>("/reports/latest"),
  reportHistory: (limit = 50) => getJson<Report[]>("/reports/history", { limit }),
  ollamaStatus: () => getJson<unknown>("/reports/ollama/status"),
  taskLogs: () => getJson<unknown[]>("/tasks/logs"),
  availableTasks: () =>
    getJson<Array<{ task_name: string; description: string; priority: string; scenario: string }>>("/tasks/available"),
  runTask: (task: string) => postJson<unknown>(`/tasks/run/${task}`),
  enqueueTask: (task: string) => postJson<unknown>(`/tasks/enqueue/${task}`),
};
