const FIELD_LABELS: Record<string, string> = {
  id: "ID",
  fund_code: "基金代码 (fund_code)",
  fund_name: "基金名称 (fund_name)",
  industry: "行业/主题 (industry)",
  group_name: "分组 (group_name)",
  note: "备注 (note)",
  is_active: "启用状态 (is_active)",
  nav_date: "净值日期 (nav_date)",
  unit_nav: "单位净值 (unit_nav)",
  accumulated_nav: "累计净值 (accumulated_nav)",
  daily_return: "日涨跌幅 (daily_return)",
  source: "来源 (source)",
  calc_date: "计算日期 (calc_date)",
  return_1w: "近1周收益 (return_1w)",
  return_1m: "近1月收益 (return_1m)",
  return_3m: "近3月收益 (return_3m)",
  return_6m: "近6月收益 (return_6m)",
  return_1y: "近1年收益 (return_1y)",
  max_drawdown_1y: "近1年最大回撤 (max_drawdown_1y)",
  volatility_1y: "近1年波动率 (volatility_1y)",
  sharpe_1y: "近1年夏普比率 (sharpe_1y)",
  win_rate_1y: "近1年胜率 (win_rate_1y)",
  score: "评分 (score)",
  total_score: "总分 (total_score)",
  rating: "评级 (rating)",
  reason: "理由 (reason)",
  score_date: "评分日期 (score_date)",
  score_change: "分数变化 (score_change)",
  trend_direction: "趋势方向 (trend_direction)",
  rating_changed: "评级是否变化 (rating_changed)",
  previous_rating: "上一评级 (previous_rating)",
  return_score: "收益分 (return_score)",
  drawdown_score: "回撤分 (drawdown_score)",
  volatility_score: "波动分 (volatility_score)",
  stability_score: "稳定性分 (stability_score)",
  size_score: "规模分 (size_score)",
  trade_status_score: "交易状态分 (trade_status_score)",
  fund_count: "基金数量 (fund_count)",
  avg_score: "平均评分 (avg_score)",
  position_value: "持仓市值 (position_value)",
  position_weight: "持仓占比 (position_weight)",
  task_name: "任务名称 (task_name)",
  status: "状态 (status)",
  message: "消息 (message)",
  started_at: "开始时间 (started_at)",
  finished_at: "结束时间 (finished_at)",
  duration_seconds: "耗时秒数 (duration_seconds)",
  created_at: "创建时间 (created_at)",
  alert_type: "预警类型 (alert_type)",
  alert_level: "预警级别 (alert_level)",
  title: "标题 (title)",
  content: "内容 (content)",
  is_read: "已读状态 (is_read)",
  fund_a: "基金A (fund_a)",
  fund_b: "基金B (fund_b)",
  correlation: "相关系数 (correlation)",
  return_a: "基金A日涨跌幅 (return_a)",
  return_b: "基金B日涨跌幅 (return_b)",
  base_url: "服务地址 (base_url)",
  configured_model: "配置模型 (configured_model)",
  timeout_seconds: "超时时间 (timeout_seconds)",
  available_models: "本地模型列表 (available_models)",
  model_available: "模型是否可用 (model_available)",
};

export function fieldLabel(key: string): string {
  return FIELD_LABELS[key] || `${key} (${key})`;
}
